# Generated by Django 4.2.5 on 2023-10-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0007_remove_amigo_ano_remove_amigo_assentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='Capa',
        ),
        migrations.AddField(
            model_name='amigo',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='avatar'),
        ),
    ]
