# Generated by Django 4.2.5 on 2023-10-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0008_remove_amigo_capa_amigo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='Avatar',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='Duração',
        ),
        migrations.AddField(
            model_name='amigo',
            name='Capa',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='capa'),
        ),
        migrations.AddField(
            model_name='amigo',
            name='Duraçao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Duraçao'),
        ),
    ]
